apiVersion: v1
kind: Secret
metadata:
  name: nexra-secrets
  namespace: nexra
type: Opaque
stringData:
  AUTH_DB_PASSWORD: "change-me"
  AUTH_OAUTH2_KEYSTORE_PASSWORD: "change-me"
  AUTH_OAUTH2_KEY_PASSWORD: "change-me"
  AUTH_REDIS_PASSWORD: "change-me"
  AUTH_SMTP_PASSWORD: "change-me"
