spring.application.name=nexra
spring.threads.virtual.enabled=true

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.endpoint.health.show-details=never
management.endpoint.health.group.liveness.include=livenessState,ping
management.endpoint.health.group.readiness.include=readinessState,db

logging.level.root=INFO
logging.level.com.nexra.hrms.nexra.modules.auth=INFO
logging.pattern.level=%5p [req:%X{requestId:-}]

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.auth.jwt.secret=${AUTH_JWT_SECRET:}
app.auth.jwt.access-token-minutes=30
app.auth.jwt.refresh-token-days=14
app.auth.otp-expiry-minutes=10
app.auth.link-expiry-minutes=20
app.auth.bootstrap.enabled=false

app.auth.security.login-max-failures=5
app.auth.security.login-lock-minutes=30
app.auth.security.login-failure-window-minutes=15
app.auth.security.otp-request-limit=5
app.auth.security.otp-window-minutes=10
app.auth.security.redis-enabled=false
app.auth.security.cors-allowed-origins=http://localhost:4200,http://127.0.0.1:4200,http://localhost:5173,http://127.0.0.1:5173
app.auth.cookie.refresh-token-name=nexra_refresh_token
app.auth.cookie.same-site=Lax
app.auth.cookie.secure=false
app.auth.cookie.path=/

app.auth.mail.enabled=false
app.auth.mail.from=noreply@nexra.local

app.auth.oauth2.default-client-id=nexra-web-client
app.auth.oauth2.default-client-secret=${AUTH_OAUTH2_DEFAULT_CLIENT_SECRET:}
app.auth.oauth2.default-redirect-uri=http://localhost:3000/callback
app.auth.oauth2.issuer=${AUTH_OAUTH2_ISSUER:http://localhost:8081}
app.auth.oauth2.ephemeral-key-enabled=false
app.auth.oauth2.keystore-location=${AUTH_OAUTH2_KEYSTORE_LOCATION:}
app.auth.oauth2.keystore-password=${AUTH_OAUTH2_KEYSTORE_PASSWORD:}
app.auth.oauth2.keystore-key-alias=${AUTH_OAUTH2_KEY_ALIAS:}
app.auth.oauth2.keystore-key-password=${AUTH_OAUTH2_KEY_PASSWORD:}
