-- Historical placeholder migration kept for backward-compatible Flyway version ordering.
-- Persistent payroll storage is implemented in V21 and hardened by subsequent migrations.
-- Author: niteshjaitwar
