ALTER TABLE tenants ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE user_accounts ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE verification_tokens ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE refresh_tokens ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE user_product_access ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE ec_organization_profiles ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE ec_departments ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE ec_employees ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE at_shifts ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE at_records ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE lv_leave_types ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE lv_holidays ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE lv_balances ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE lv_leave_requests ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE ts_projects ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE ts_entries ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE onboarding_plans ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE onboarding_tasks ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE performance_goals ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE performance_reviews ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE recruitment_jobs ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE recruitment_candidates ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE recruitment_candidate_stage_history ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE ex_categories ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE ex_claims ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE ex_claim_items ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE payroll_organization_profiles ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE payroll_employee_profiles ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
